### ISSUE TITLE
Most commands not doing anything

### ISSUE THREAD

**Issue by xamionex** [MineBartekSA/FACommands#1]
I'm hosting a server and i've tried your plugin and it's pretty nice so far but the problem is commands that are like player interacting with another player don't work (like /kiss /hug /slay and such) they just go through and nothing happens

**Comment by MineBartekSA** [comment]
Sorry for the wait, but this issue was fixed in commit 6cc620679597434b48cb88a4061b993e91c6896d
Update your plugin to version 1.7.1
You can find it on this repo (in the releases), or you can wait for the link to be updated on the [Official TShock Plugins](https://github.com/Pryaxis/Plugins) repo
